cargo-features = ["panic-immediate-abort"]

[package]
name = "update-ip"
version = "0.1.0"
edition = "2024"

[features]
default = ["resolver-opendns", "provider-cloudflare"]

resolver-opendns = []

provider-cloudflare = []

[profile.release]
lto = true
strip = true
panic = "immediate-abort"
codegen-units = 1
